
server:
  port: 0
#activemq.topic.product-inform=product.order.inform
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: shopping-failed-message-resolver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualhost: homework

    listener:
      simple:
        default-requeue-rejected: false


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

app:
  rabbitmq:
    order:
      exchange: order.exchange
      queue: order.queue
      routingKey: order.routingKey
